/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.company.messenger.client.gateway.api;

import com.company.messenger.client.gateway.model.Version;
import io.swagger.annotations.*;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Validated
@Api(value = "version", description = "the version API")
public interface VersionApi {

    /**
     * GET /version : Запрос версии API
     *
     * @return OK (status code 200)
     */
    @ApiOperation(value = "Запрос версии API", nickname = "getVersion", notes = "", response = Version.class, tags={ "common", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Version.class) })
    @RequestMapping(value = "/version",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Version> getVersion();

}
